---

- hosts: all
  tasks:
    - name: Insert the Tahoe devstack hostnames
      blockinfile:
        path: /etc/hosts
        block: |
          #
          # Those configurations are temporary and might removed
          # or changed based on your devstack configurations.

          {{ IP_ADDRESS }} {{ TAHOE_HOST_NAME }}
          {{ IP_ADDRESS }} edx.devstack.lms
          {{ IP_ADDRESS }} red.localhost
          {{ IP_ADDRESS }} blue.localhost
          {{ IP_ADDRESS }} green.localhost
      become: yes
      tags:
        - hosts_update

    - name: Remove Tahoe devstack hostnames
      blockinfile:
        path: "{{ item }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: ""
      become: yes
      with_items:
        - /etc/hosts
        - ~/.ssh/config
      tags:
        - hosts_revert

    - name: Configure SSH agent forwarding
      blockinfile:
        path: ~/.ssh/config
        create: yes
        block: |
          Host devstack
            HostName {{ IP_ADDRESS }}
            User {{ USER }}
            IdentityFile {{ SSH_KEY }}
            ForwardAgent yes
      tags:
        - ssh_config

    - name: Get the remote instance host key
      shell: ssh-keyscan -t rsa {{ IP_ADDRESS }}
      register: host_key
      until: host_key.stdout.find(IP_ADDRESS) != -1
      retries: 10
      delay: 10
      ignore_errors: yes
      tags:
        - ssh_config

    - name: Configure SSH known hosts
      blockinfile:
        path: ~/.ssh/known_hosts
        create: yes
        block: "{{ host_key.stdout }}"
      tags:
        - ssh_config
